### ISSUE TITLE
In Apps targeting Android 13, openPicker is not working. It does not ask for permission and camera roll does not open.

### ISSUE THREAD

**Issue by dtumonasingh** [ivpusic/react-native-image-crop-picker#1849]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.?.?
- react-native v0.?.?

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by shawarmaz** [comment]
@dtumonasingh what device are you testing on ?

**Comment by dtumonasingh** [comment]
> @dtumonasingh what device are you testing on ?

I am testing on Pixel 4 simulator, the app targets Android 13 and the device also is on Android 13. When the app targets Android 12, no matter what the device, the openPicker ask for permission, only on Android 13 we see this problem. My guess is it has something to do with the WRITE_EXTERNAL_STORAGE permission it asks for,

**Comment by dtumonasingh** [comment]
Adding ACESS_MEDIA_IMAGES instead of WRITE_EXTERNAL_STORAGE at this [line](https://github.com/ivpusic/react-native-image-crop-picker/blob/master/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java#L406) helped me get the permission dialog when opening gallery using the openPicker function.  I am not sure what other permission is also needed to be added in place of WRITE_EXTERNAL_STORAGE to give write permission in case of Apps targeting Android 13.

According to this [Bug](https://issuetracker.google.com/issues/228868661#comment11) from Android 13 the WRITE_EXTERNAL_STORAGE permission does not contain the READ_EXTERNAL_STORAGE permission implicitly.

**Comment by shawarmaz** [comment]
@dtumonasingh can confirm this works. May want to PR the docs. Thanks a ton 🥳

**Comment by Talhafayyaz11** [comment]
What is the update here. Can guys please merge the above PR. So i can use this in apps targeting android 13.

**Comment by Talhafayyaz11** [comment]
i tried to run on real device with appropriate permission and it works find

**Comment by berk9595** [comment]
adding this into **app/src/main/AndroidManifest.xml** fixed mine
<uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>

**Comment by berk9595** [comment]
<uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/> fixed mine

**Comment by berk9595** [comment]
`<uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>` fixed mine.

**Comment by SMARTMICROWORLD** [comment]
Uninstall using `npm uninstall react-native-image-crop-picker` and again install using `npm i react-native-image-crop-picker` and don't forget to add `<uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>` to android/app/src/main/AndroidManifest.xml. Have a gread day!😊

**Comment by CodingWithNobody** [comment]
Check this https://www.youtube.com/watch?v=Bx_gwRODtlY

**Comment by ayoubshah2720** [comment]
Added these permissions works for **Android 13**
<uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.CAMERA" />

**Comment by vishalSharmaCfcs** [comment]
> `<uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>`
> 
> Adding this line into android/app/src/main/AndroidManifest.xml fixed mine.

Working for me too

**Comment by 1Jesper1** [comment]
> > `<uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>`
> > Adding this line into android/app/src/main/AndroidManifest.xml fixed mine.
> 
> Working for me too

For us also! No change required for targetsdk and gradle!

**Comment by RodolfoGS** [comment]
I recommend you to apply the patch that I mentioned in this PR https://github.com/ivpusic/react-native-image-crop-picker/pull/1973#issuecomment-1719531114 instead of add the **READ_MEDIA_IMAGES** permission since that permission is not required to open the picker.

> **Note:** If your app only needs to access images, photos, and videos, consider using the [photo picker](https://developer.android.com/about/versions/13/features/photopicker) instead of declaring the **READ_MEDIA_IMAGES** and **READ_MEDIA_VIDEO** permissions.

Source: https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions

**Comment by 1Jesper1** [comment]
> I recommend you to apply the patch that I mentioned in this PR [#1973 (comment)](https://github.com/ivpusic/react-native-image-crop-picker/pull/1973#issuecomment-1719531114) instead of add the **READ_MEDIA_IMAGES** permission since that permission is not required to open the picker.
> 
> > **Note:** If your app only needs to access images, photos, and videos, consider using the [photo picker](https://developer.android.com/about/versions/13/features/photopicker) instead of declaring the **READ_MEDIA_IMAGES** and **READ_MEDIA_VIDEO** permissions.
> 
> Source: https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions

What version do you use? Should be fixed in v0.39. https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.39.0

**Comment by RodolfoGS** [comment]
> Should be fixed in v0.39

Yes, But...

I'm using version 0.40.0, and when I implemented it, I forgot to add **android.permission.READ_MEDIA_IMAGES** to my AndroidManifest.xml (because this requirement isn't mentioned in the Readme).

Before realizing that I had missed that, I began searching for a solution and implemented another library (**react-native-image-picker**). I noticed that they could open the picker without requiring any permission on Android 13. So, I started to read their code and I noticed that they were not using the **READ_MEDIA_IMAGES** permission. Afterward, I checked the Google Documentation and found this sentence: 

> **Note:** If your app only needs to access images, photos, and videos, consider using the [photo picker](https://developer.android.com/about/versions/13/features/photopicker) instead of declaring the **READ_MEDIA_IMAGES** and **READ_MEDIA_VIDEO** permissions.

Source: https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions

That is because the picker is part of the OS and there the user can select the picture that he want, so that is the final permission (the user's selection).

So, the solution is to simply remove that permission from the code, and you won't need to ask the user for any permission.

The same can be done with opening the camera; the **CAMERA** permission is not required. I have created another PR for that, https://github.com/ivpusic/react-native-image-crop-picker/pull/1974

**Comment by Devyadav3001** [comment]
<uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/> its working android 13 but not working in android 11 
when use   this <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" /> then work  in 11 not work  in 13 plz solve my problem

**Comment by Jatindarji03** [comment]
Same problem with me also

**Comment by AmaluThomas** [comment]
Even after adding READ_MEDIA_IMAGES to manifest, still not able to select images and files in webview

**Comment by Kavinduweb** [comment]
Perhaps it seems to be a problem that arises because Android does not allow http.

Please build a new Android after changing Android settings as follows.

    android/app/src/main/AndroidManifest.xml

<application
        android:usesCleartextTraffic="true"> // you add this

</application>

**Comment by Kavinduweb** [comment]
Perhaps it seems to be a problem that arises because Android does not allow http.

Please build a new Android after changing Android settings as follows.

    android/app/src/main/AndroidManifest.xml
<application
        android:usesCleartextTraffic="true"> // you add this

</application>

**Comment by Kavinduweb** [comment]
Perhaps it seems to be a problem that arises because Android does not allow http.

Please build a new Android after changing Android settings as follows.

    android/app/src/main/AndroidManifest.xml
`<application
        android:usesCleartextTraffic="true"> // you add this
...
</application>`
