### ISSUE TITLE
RN 0.40 support

### ISSUE THREAD

**Issue by jjdp** [ivpusic/react-native-image-crop-picker#194]
update IOS import headers for

https://github.com/facebook/react-native/commit/e1577df1fd70049ce7f288f91f6e2b18d512ff4d

**Comment by ivpusic** [comment]
fixed in https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.12.0

**Comment by superandrew213** [comment]
@ivpusic why was this added?
https://github.com/ivpusic/react-native-image-crop-picker/blob/master/ios/ImageCropPicker.h#L13-L16

To work for < RN0.40.0?

**Comment by ivpusic** [comment]
yes

**Comment by superandrew213** [comment]
This never worked for me. When I was on RN0.39.2 I had to use react-native-image-crop-picker@0.11.x.

I just upgraded to RN0.42.3 and latest react-native-image-crop-picker but it's still not working. It says it can't find RCTImageLoader.h.

Are you on the latest version and is it working fine for you?

**Comment by ivpusic** [comment]
I am on latest RN version and latest RNICP version and everything works well for me. However when I migrated to 0.40 I also had some issues. Check for my solution here http://stackoverflow.com/questions/41477241/react-native-xcode-upgrade-and-now-rctconvert-h-not-found

**Comment by superandrew213** [comment]
hmm tried this but still getting the same issue. `RCTImageLoader.h` not found. I looked at some other projects and they check for `<React/RCTBridge.h>` instead of `RCTBridgeModule.h`. For some reason this works for me: 
```
#if __has_include(<React/RCTBridge.h>)
#import <React/RCTBridgeModule.h>
#import <React/RCTImageLoader.h>
#else
#import "RCTBridgeModule.h"
#import "RCTImageLoader.h"
#endif
```
