### ISSUE TITLE
Uploading multiple photos disregards maxWidth/Height props

### ISSUE THREAD

**Issue by andrewfluck** [ivpusic/react-native-image-crop-picker#532]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.18.1
- react-native v0.50.3

### Platform
Tell us to which platform this issue is related
- Android 8.0

### Expected behaviour
When selecting multiple images, they should follow the `compressImageMaxWidth` `compressImageMaxHeight` rules.

### Actual behaviour
When selecting multiple images, they should follow the `compressImageMaxWidth` `compressImageMaxHeight` but don't and instead end up uploading them to original size which for a startup, is bad.

### Steps to reproduce
1. Select multiple photos in your file browser window
2. Hit Ok
3. That's it, make sure to have the aforementioned props to see the bug in action.

**Comment by ivpusic** [comment]
do you have some time to investigate this?

**Comment by andrewfluck** [comment]
No unfortunately, I don't. I'm on a tight schedule and we need this app to be done very soon.

**Comment by ChrisLahaye** [comment]
@ivpusic I have the same problem. What additional information can I give you?

**Comment by ChrisLahaye** [comment]
@ivpusic I have tracked the problem down, photos are being resized but just to the wrong dimensions. Its caused by false calculations in the compression library.

Its fixed in the fork https://github.com/aftabsikander/Compressor and a pull request has been made already https://github.com/zetbaitsu/Compressor/pull/82.

**Comment by ShreyashPromact** [comment]
@andrewfluck Can you please check above PR and if it is fine, can you please merge it with the library.
Normally user uses the latest OS. Now if it is not working on such device then there is no benefit to use this library.

**Comment by angeloocana** [comment]
not working for me:

```js
{
      includeBase64: true,
      cropping: false,
      // width: 640,
      // height: 640,
      multiple: true,
      compressImageMaxWidth: 1200,
      compressImageMaxHeight: 1200,
      compressImageQuality: 0.8,
      mediaType: 'photo',

    }
```

**Comment by DISKONEKTeD** [comment]
Still experiencing similar issue as well, that PR request seems to have been ignored

**Comment by bonesyblue** [comment]
I've created a PR, which I think may relate to this issue. Feel free to check it out and leave feedback 👍
